library(shiny)
library(shinythemes)
library(shinyjs)
library(data.table)
library(gtools)
library(DT)

# Define list of comparators (labels and values)
comparators = c(
  "Nivolumab" = "nivolumab_monotherapy",
  "Cabozantinib plus nivolumab" = "cabozantinib_plus_nivolumab",
  "Nivolumab plus ipilimumab" = "nivolumab_plus_ipilimumab",
  "Lenvatinib plus pembrolizumab" = "lenvatinib_plus_pembrolizumab",
  "Avelumab plus axitinib" = "avelumab_plus_axitinib",
  "Pazopanib" = "pazopanib",
  "Tivozanib" = "tivozanib",
  "Sunitinib" = "sunitinib",
  "Cabozantinib" = "cabozantinib",
  "Lenvatinib plus everolimus" = "lenvatinib_plus_everolimus",
  "Everolimus" = "everolimus",
  "Axitinib" = "axitinib",
  "Sorafenib" = "sorafenib",
  "Best supportive care" = "placebo_BSC")

# Import the sequencing functions
f_path = "../3_Functions"
source(file.path(f_path, "sequencing/sequences.R"))

# Import the fixed parameters (from .csv generated by convert_to_csv.R)
# and save as i, which is a list of lists
lists_df <- read.csv("data/lists.csv")
i <- lapply(lists_df, function(x) unlist(x)[!is.na(unlist(x))])
names(i) <- names(lists_df)

# Create user interface (layout and appearance of app)
ui <- fluidPage(
  # Website theme
  theme = shinytheme("cosmo"),

  # Allows some JavaScript operations           
  useShinyjs(),
  
  # App title
  titlePanel(
    title = span(img(src="exeter_pentag_small.png", height=60, style = "margin-right: 20px;"),
                 "Exeter Oncology Model: Renal Cell Carcinoma edition"),
    windowTitle = "EOM:RCC"),
  
  # Sidebar layout with input and output definitions
  sidebarLayout(
    
    # Sidebar panel for inputs
    sidebarPanel(
      
      h1("Inputs"),
  
      actionButton("reset", "Reset"),
      selectInput("i_nr_population", "Number of populations",
                  c(1, 2, 3, 4), selected = 4),
      selectInput("R_maxlines", "Max lines within the R model",
                  c(3, 4), selected = 4),
      selectizeInput("List_comparators", "Comparator list",
                     choices = comparators,
                     selected = comparators,
                     multiple = TRUE,
                     options = list(plugins = list("remove_button"))),
      actionButton("seq_button", "Find possible treatment sequences")
      
    ),
    
    # Main panel for displaying outputs
    mainPanel(
      h1("Results"),
      verbatimTextOutput("describe"),
      DT::DTOutput("sequences"),
      
    )
  )
)

# Instructions for building the app
server <- function(input, output) {

  # Reactive expression to produce data table of valid sequences for each population
  valid_seq <- reactive({

    # All possible treatment combinations
    all_seq <- as.data.frame(f_generate_sequences(
      comparators = input$List_comparators,
      maxlines = as.numeric(input$R_maxlines)))
  
    seqs <- NULL
    # Loop through each population
    for (population in 1:input$i_nr_population) {
      s <- f_path_tx_restrict(
        sequences                = all_seq,
        allowed                  = f_get_allowed_lists(i, population), #overall list of allowed drugs in this popn
        L1                       = f_get_L1_lists(i, population), # 1L drugs allowed in this popn
        L2                       = f_get_L2_lists(i, population), # 2L drugs allowed in this popn
        L3                       = f_get_L3_lists(i, population), # 3L drugs allowed in this popn
        L4                       = f_get_L4_lists(i, population), # 4L drugs allowed in this popn
        only_after               = f_get_only_after_lists(i, population), #list of restrictions where tx can be only after the listed txs
        not_immediate_after      = f_get_not_immediate_after_lists(i, population), #list of restrictions where tx can be only immediately before the listed txs
        one_in_list              = f_get_one_in_list_lists(i, population), #list of restrictions where only one of the tx in each list is allowed 
        only_after_one           = f_get_only_after_one_lists(i, population), #list of restrictions where only one of the listed treatments is allowed prior to current therapy 
        L2_only_after            = f_get_2L_only_after_lists(i, population), #list of 2L+ restrictions: if drug is used 2L, 3L or 4L, can only be after drug x
        L2_only_immediate_after  = f_get_2L_only_immediate_after_lists(i, population), #list of 2L+ restrictions: if drug is used 2L, 3L or 4L, can only be immediately after drug x
        L2_only_one              = f_get_2L_only_one_lists(i, population) #list of 2L+ drugs where only one of them allowed in a given sequence
      )
      s <- cbind(rep(paste0("pop", population),nrow(s)), s)
      colnames(s) <- paste0('V', seq_len(ncol(s)))
      seqs <- rbind(seqs, s)
    }
    return(seqs)
  }) |>
    bindEvent(input$seq_button)

  # Render table
  output$describe <- renderText(paste0(
    "There are ", nrow(valid_seq()), " possible treatment sequences."))
  output$sequences <- DT::renderDT(
    {valid_seq()},
    rownames = FALSE,
    options = list(autoWidth = TRUE)) #, stringsAsFactors = TRUE),
    #filter = list(position = "top"))

  # If click button, reset inputs
  observeEvent(input$reset, {
    reset("R_maxlines")
    reset("List_comparators")
    hide("sequences")
    hide("describe")
  })
  
  # If click button, show main panel outputs
  observeEvent(input$seq_button, {
    show("sequences")
    show("describe")
  })
  
  # If change inputs, hide main panel outputs
  observeEvent(input$i_nr_population, {
    hide("sequences")
    hide("describe")
  })
  observeEvent(input$R_maxlines, {
    hide("sequences")
    hide("describe")
  })
  observeEvent(input$List_comparators, {
    hide("sequences")
    hide("describe")
  })
}

# Create the shiny app
shinyApp(ui, server)