# ==========================================================
# Simple shiny web app to identify valid treatment sequences
# ==========================================================

# Load required packages
library(shiny)
library(shinythemes)
library(shinyjs)
library(data.table)
library(gtools)
library(DT)
library(markdown)
library(openxlsx)

# ======
# Inputs
# ======

# Define list of comparators (labels and values)
comparators_choice = c(
  "Nivolumab" = "nivolumab_monotherapy",
  "Cabozantinib plus nivolumab" = "cabozantinib_plus_nivolumab",
  "Nivolumab plus ipilimumab" = "nivolumab_plus_ipilimumab",
  "Lenvatinib plus pembrolizumab" = "lenvatinib_plus_pembrolizumab",
  "Avelumab plus axitinib" = "avelumab_plus_axitinib",
  "Pazopanib" = "pazopanib",
  "Tivozanib" = "tivozanib",
  "Sunitinib" = "sunitinib",
  "Cabozantinib" = "cabozantinib",
  "Lenvatinib plus everolimus" = "lenvatinib_plus_everolimus",
  "Everolimus" = "everolimus",
  "Axitinib" = "axitinib")
# Sorafenib and best supportive care are included by default
comparators_default = c("sorafenib", "placebo_BSC")

# Define list of populations (labels and values)
populations = c(
  "Population 1" = 1,
  "Population 2" = 2,
  "Population 3" = 3,
  "Population 4" = 4)

# Import the sequencing functions
source("sequences.R")

# Import the fixed parameters (from .csv generated by convert_to_csv.R)
# and save as i, which is a list of lists
lists_df <- read.csv("data/lists.csv")
i <- lapply(lists_df, function(x) unlist(x)[!is.na(unlist(x))])
names(i) <- names(lists_df)

# =============================================
# User interface (layout and appearance of app)
# =============================================

ui <- fluidPage(
  # Website theme
  theme = shinytheme("simplex"),

  # Allows some JavaScript operations           
  useShinyjs(),
  
  # App title with logo
  titlePanel(
    title = span(img(src="exeter_pentag_small.png", height=60, style = "margin-right: 20px;"),
                 "Exeter Oncology Model: Renal Cell Carcinoma edition"),
    windowTitle = "EOM:RCC"),
  
  # Introductory paragraph
  includeMarkdown("txt/intro.md"),
  
  # Header
  h2("Find valid treatment sequences"),

  # Sidebar layout with input and output definitions
  sidebarLayout(
    
    # Sidebar panel for inputs
    sidebarPanel(
      
      h3("Inputs"),

      # Blank space before button
      headerPanel(""),

      # Button to reset inputs to default ("selected")
      actionButton(inputId = "reset",
                   label = "Reset inputs"),

      # Blank space after button
      headerPanel(""),

      # Number of populations (pop1-pop4)
      selectizeInput(inputId = "populations",
                     label = "Patient populations",
                     choices = populations,
                     selected = populations,
                     multiple = TRUE,
                     options = list(plugins = list("remove_button"))),
  
      # Number of treatment lines
      selectInput(inputId = "R_maxlines",
                  label = "Max lines within the R model",
                  choices = c(3, 4),
                  selected = 4),

      # Treatments
      selectizeInput(inputId = "chosen_comparators",
                     label = "Comparator list (includes sorafenib and best supportive care by default)",
                     choices = comparators_choice,
                     selected = comparators_choice,
                     multiple = TRUE,
                     options = list(plugins = list("remove_button"))),
  
      # Button to trigger creation of table of valid sequences
      actionButton(inputId = "seq_button",
                   label = "Find possible treatment sequences")
      
    ),
    
    # Main panel for displaying outputs
    mainPanel(
      h3("Results"),
      verbatimTextOutput("describe"),
      DT::DTOutput("sequences"),
      downloadButton(outputId = "download_table",
                     label = "Download table as an excel file")
      
    )
  )
)

# ==========================================
# Server (instructions for building the app)
# ==========================================

server <- function(input, output) {

  # Reactive expression to produce data table of valid sequences for each population
  valid_seq <- reactive({

    # Find all possible treatment combinations, including sorafeinb and
    # best supportive care alongside the list of chosen comparators
    all_seq <- as.data.frame(f_generate_sequences(
      comparators = append(input$chosen_comparators, comparators_default),
      maxlines = as.numeric(input$R_maxlines)))
  
    seqs <- NULL
    # Loop through each population
    for (population in input$populations) {
      s <- f_path_tx_restrict(
        sequences                = all_seq,
        allowed                  = f_get_allowed_lists(i, population), #overall list of allowed drugs in this popn
        L1                       = f_get_L1_lists(i, population), # 1L drugs allowed in this popn
        L2                       = f_get_L2_lists(i, population), # 2L drugs allowed in this popn
        L3                       = f_get_L3_lists(i, population), # 3L drugs allowed in this popn
        L4                       = f_get_L4_lists(i, population), # 4L drugs allowed in this popn
        only_after               = f_get_only_after_lists(i, population), #list of restrictions where tx can be only after the listed txs
        not_immediate_after      = f_get_not_immediate_after_lists(i, population), #list of restrictions where tx can be only immediately before the listed txs
        one_in_list              = f_get_one_in_list_lists(i, population), #list of restrictions where only one of the tx in each list is allowed 
        only_after_one           = f_get_only_after_one_lists(i, population), #list of restrictions where only one of the listed treatments is allowed prior to current therapy 
        L2_only_after            = f_get_2L_only_after_lists(i, population), #list of 2L+ restrictions: if drug is used 2L, 3L or 4L, can only be after drug x
        L2_only_immediate_after  = f_get_2L_only_immediate_after_lists(i, population), #list of 2L+ restrictions: if drug is used 2L, 3L or 4L, can only be immediately after drug x
        L2_only_one              = f_get_2L_only_one_lists(i, population) #list of 2L+ drugs where only one of them allowed in a given sequence
      )
      s <- cbind(rep(paste0("pop", population),nrow(s)), s)
      colnames(s) <- paste0('V', seq_len(ncol(s)))
      seqs <- rbind(seqs, s)
    }
    return(seqs)
  }) |>
    bindEvent(input$seq_button)

  # Render table
  output$describe <- renderText(paste0(
    "There are ", nrow(valid_seq()), " possible treatment sequences."))
  output$sequences <- DT::renderDT(
    {valid_seq()},
    rownames = FALSE,
    options = list(autoWidth = TRUE)) #, stringsAsFactors = TRUE),
    #filter = list(position = "top"))

  # If click button, reset inputs
  observeEvent(input$reset, {
    reset("populations")
    reset("R_maxlines")
    reset("chosen_comparators")
    hide("sequences")
    hide("describe")
    hide("download_table")
  })
  
  # If click button, show main panel outputs
  observeEvent(input$seq_button, {
    show("sequences")
    show("describe")
    show("download_table")
  })
  
  # If change inputs, hide main panel outputs
  observeEvent(input$populations, {
    hide("sequences")
    hide("describe")
    hide("download_table")
  })
  observeEvent(input$R_maxlines, {
    hide("sequences")
    hide("describe")
    hide("download_table")
  })
  observeEvent(input$chosen_comparators, {
    hide("sequences")
    hide("describe")
    hide("download_table")
  })

  # If click download button, download .xlsx file with table
  output$download_table <- downloadHandler(
    filename = "valid_sequences.xlsx",
    content = function(file) {
      # Write the dataset to the file that will be download
      write.xlsx(valid_seq(), file)
    }
  )
}

# ====================
# Create the shiny app
# ====================

shinyApp(ui, server)