project:
  type: website
  render:
    - "*.qmd"

website:
  title: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exeter Oncology Model: Renal Cell Carcinoma edition"
  # Adds edit and issue buttons to footer
  repo-url: https://github.com/pythonhealthdatascience/stars-eom-rcc/
  repo-actions: [edit, issue]
  # Create navbar across top of page
  navbar:
    collapse: false
    logo: "images/exeter_pentag_small.png"
    logo-alt: "Exeter PenTAG"
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-eom-rcc/
  # Create sidebar with page navigation
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - pages/acronyms.qmd
      - section: "Context"
        contents:
          - pages/appraisals.qmd
          - pages/publication.qmd
      - section: "Model overview"
        contents:
          - text: "Detailed summary"
            href: pages/model_overview.qmd
          - text: "Plain english summary"
            href: pages/plain_english.qmd
      - text: "Installation"
        href: pages/installation.qmd
      - section: "Code walkthrough"
        contents:
          - text: "Input data"
            href: pages/input_data.qmd
          - pages/report.qmd
      - section: "Annotated reporting guidelines"
      - section: "Model validation"
      - pages/license.qmd
      - pages/citation.qmd
      - section: "Contributing"
      - text: "Changelog"
        href: pages/changelog.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
