project:
  type: website

website:
  title: "Exeter Oncology Model: Renal Cell Carcinoma edition"
  # Adds edit and issue buttons to footer
  repo-url: https://github.com/pythonhealthdatascience/stars-eom-rcc/
  repo-actions: [edit, issue]
  # Create navbar across top of page
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-eom-rcc/
  # Create sidebar with page navigation
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - pages/acronyms.qmd
      - section: "Context"
        contents:
          - pages/appraisals.qmd
          - pages/publication.qmd
          - text: "Model plain english summary"
            href: pages/plain_english.qmd
      - section: "Installation"
      - section: "Model code walkthrough"
      - section: "Annotated reporting guidelines"
      - section: "Model validation"
      - pages/license.qmd
      - pages/citation.qmd
      - section: "Contributing"
      - text: "Changelog"
        href: pages/changelog.qmd

format:
  html:
    theme: cosmo
    toc: true
